# NOTE: update this with your service name
service: crs-jatayu



plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: serverlessUser
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  # environment:
  #   DATABASE_URL: ${env:DATABASE_URL}
   

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
  addState: 
    handler: lambdas/state/addState.handler
    events:
      - http:
          path: /state/add
          method: post
  deleteState:
    handler: lambdas/state/deleteState.handler
    events:
      - http:
          path: /state/delete/{id}
          method: delete
          cors: true
  getState:
    handler: lambdas/state/getStates.handler
    events:
      - http:
          path: /states
          method: get
          cors: true
  addCity:
    handler: lambdas/city/addCity.handler
    events:
      - http:
          path: /city/add
          method: post
          cors: true
  deleteCity:
    handler: lambdas/city/deleteCity.handler
    events:
      - http:
          path: /city/delete/{id}
          method: delete
          cors: true
  getCities:
    handler: lambdas/city/getCities.handler
    events:
      - http:
          path: /cities
          method: get
          cors: true
  addHotel:
    handler: lambdas/hotel/addHotel.handler
    events:
    - http:
        path: /hotel/add
        method: post
        cors: true
  deleteHotel:
    handler: lambdas/hotel/deleteHotel.handler
    events:
      - http:
          path: /hotel/delete/{id}
          method: delete
          cors: true
  getHotels:
    handler: lambdas/hotel/getHotels.handler
    event:
      - http:
          path: /hotels
          method: get
          cors: true
  updateHotel:
    handler: lambdas/hotel/updateHotel.handler
    events:
      - http:
          path: /hotel/update/{id}
          method: patch
          cors: true
  addRoom:
    handler: lambdas/room/addRoom.handler
    events:
      - http:
          path: /room/add
          method: post
          cors: true
  deleteRoom:
    handler: lambdas/room/deleteRoom.handler
    events:
      - http:
          path: /room/delete/{id}
          method: delete
          cors: true
  getRooms:
    handler: lambdas/room/getRooms.handler
    events:
      - http:
          path: /rooms
          method: get
          cors: true
  updateRoom:
    handler: lambdas/room/updateRoom.handler
    events:
      - http:
          path: /room/update/{id}
          method: patch
          cors: true
      
      
      
      

      
      
      
    

      
      
          
      

      
      


package:
  individually: true
  exclude:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - 'src/**/*'
    - '*.eslint'
