service: crs-jatayu

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: serverlessUser
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true

  # State
  addState:
    handler: lambdas/state/addState.handler
    events:
      - http:
          path: /state/add
          method: post
          cors: true
  deleteState:
    handler: lambdas/state/deleteState.handler
    events:
      - http:
          path: /state/delete/{id}
          method: delete
          cors: true
  getStates:
    handler: lambdas/state/getStates.handler
    events:
      - http:
          path: /states
          method: get
          cors: true

  # City
  addCity:
    handler: lambdas/city/addCity.handler
    events:
      - http:
          path: /city/add
          method: post
          cors: true
  deleteCity:
    handler: lambdas/city/deleteCity.handler
    events:
      - http:
          path: /city/delete/{id}
          method: delete
          cors: true
  getCities:
    handler: lambdas/city/getCities.handler
    events:
      - http:
          path: /cities
          method: get
          cors: true

  # Hotel
  addHotel:
    handler: lambdas/hotel/addHotel.handler
    events:
      - http:
          path: /hotel/add
          method: post
          cors: true
  deleteHotel:
    handler: lambdas/hotel/deleteHotel.handler
    events:
      - http:
          path: /hotel/delete/{id}
          method: delete
          cors: true
  getHotels:
    handler: lambdas/hotel/getHotels.handler
    events:
      - http:
          path: /hotels
          method: get
          cors: true
  updateHotel:
    handler: lambdas/hotel/updateHotel.handler
    events:
      - http:
          path: /hotel/update/{id}
          method: patch
          cors: true

  # Room
  addRoom:
    handler: lambdas/room/addRoom.handler
    events:
      - http:
          path: /room/add
          method: post
          cors: true
  deleteRoom:
    handler: lambdas/room/deleteRoom.handler
    events:
      - http:
          path: /room/delete/{id}
          method: delete
          cors: true
  getRooms:
    handler: lambdas/room/getRooms.handler
    events:
      - http:
          path: /rooms
          method: get
          cors: true
  updateRoom:
    handler: lambdas/room/updateRoom.handler
    events:
      - http:
          path: /room/update/{id}
          method: patch
          cors: true

  # Availability
  addAvailability:
    handler: lambdas/availablity/addAvailablity.handler
    events:
      - http:
          path: /availability/add
          method: post
          cors: true
  updateAvailability:
    handler: lambdas/availablity/updateAvailablity.handler
    events:
      - http:
          path: /availability/update
          method: patch
          cors: true

  # Booking
  createBooking:
    handler: lambdas/booking/createBooking.handler
    events:
      - http:
          path: /booking/create
          method: post
          cors: true
  cancelBooking:
    handler: lambdas/booking/cancelBooking.handler
    events:
      - http:
          path: /booking/cancel/{id}
          method: delete
          cors: true

  # Facility Types
  addFacType:
    handler: lambdas/faucility/addFacType.handler
    events:
      - http:
          path: /factype/add
          method: post
          cors: true
  deleteFacType:
    handler: lambdas/faucility/deleteFacType.handler
    events:
      - http:
          path: /factype/delete/{id}
          method: delete
          cors: true
  getFacTypes:
    handler: lambdas/faucility/getFacTypes.handler
    events:
      - http:
          path: /factypes
          method: get
          cors: true

  # Facility
  addFacility:
    handler: lambdas/faucility/addFacility.handler
    events:
      - http:
          path: /facility/add
          method: post
          cors: true
  deleteFacility:
    handler: lambdas/faucility/deleteFacility.handler
    events:
      - http:
          path: /facility/delete/{id}
          method: delete
          cors: true
  getHotelFac:
    handler: lambdas/faucility/getHotelFac.handler
    events:
      - http:
          path: /facility/room/{id}
          method: get
          cors: true

  # Sellables
  addSellables:
    handler: lambdas/sellables/addSellables.handler
    events:
      - http:
          path: /sellable/add
          method: post
          cors: true
  deleteSellable:
    handler: lambdas/sellables/deleteSellable.handler
    events:
      - http:
          path: /sellable/delete/{id}
          method: delete
          cors: true

package:
  individually: true
  exclude:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - 'src/**/*'
    - '*.eslint'
